### PR TITLE
Solved error 'Unexpected token'

### PR DESCRIPTION
**Pull request by felipewmartins**

### CODE REVIEW

**Comment by helio-frota** [comment]
hi @felipewmartins I think now is a good time to squash the commits in 1 :]

Also thanks again for the PR.

**Comment by felipewmartins** [comment]
Hi @helio-frota 
Squash done!
 :)

**Comment by helio-frota** [comment]
tip: next time ffs try to use 1 commit at time, it is good [because other projects aroud the world are doing almost the same] 

thanks!

**Comment by felipewmartins** [comment]
Thanks for the tip!
I did not know how to do before :)

**Comment by helio-frota** [comment]
@felipewmartins great nodejs guidelines : 
https://github.com/bucharest-gold/entente/blob/master/GUIDELINES.md

**Comment by felipewmartins** [comment]
Very good!
This is a good overview about the project structure.

**Pull request merged**
